format = """
$conda$python$directory$git_branch$git_state$git_status$git_metrics$hostname
$container$username$character"""

scan_timeout = 500
command_timeout = 3000

[conda]
style = 'bold green'
format = '[\($environment\)]($style) '
ignore_base=false

[directory]
truncate_to_repo = false
truncation_length = 6

[git_branch]
style = 'bold purple'
format = '[$symbol$branch$tag]($style)'
symbol = "\ue725 "

[git_status]
style = 'bold white'
format = ' ([$all_status$ahead_behind]($style))'
conflicted = '[=$count](bold red) '
ahead = '[⇡$count](bold cyan) '
behind = '[⇣$count](bold cyan) '
diverged = '[⇕⇡$ahead_count⇣$behind_count](bold cyan) '
untracked = '[?$count](bold blue) '
stashed = '[*$count](bold blue) '
modified = '[!$count](bold yellow) '
staged = '[+$count](bold green) '
renamed = '[»$count](bold green) '
deleted = '[✘$count](bold red) '

[hostname]
format = 'in [$hostname]($style)'

[python]
format = '[\($virtualenv\)]($style) '
detect_extensions = []
detect_files = []
detect_folders = []

[username]
format = '[$user]($style) '
